/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsGeneieRouteImport } from './routes/products.geneie'
import { Route as ProductsAssureRouteImport } from './routes/products.assure'

const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsGeneieRoute = ProductsGeneieRouteImport.update({
  id: '/geneie',
  path: '/geneie',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsAssureRoute = ProductsAssureRouteImport.update({
  id: '/assure',
  path: '/assure',
  getParentRoute: () => ProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/products': typeof ProductsRouteWithChildren
  '/technology': typeof TechnologyRoute
  '/products/assure': typeof ProductsAssureRoute
  '/products/geneie': typeof ProductsGeneieRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/products': typeof ProductsRouteWithChildren
  '/technology': typeof TechnologyRoute
  '/products/assure': typeof ProductsAssureRoute
  '/products/geneie': typeof ProductsGeneieRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/products': typeof ProductsRouteWithChildren
  '/technology': typeof TechnologyRoute
  '/products/assure': typeof ProductsAssureRoute
  '/products/geneie': typeof ProductsGeneieRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/products'
    | '/technology'
    | '/products/assure'
    | '/products/geneie'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/products'
    | '/technology'
    | '/products/assure'
    | '/products/geneie'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/products'
    | '/technology'
    | '/products/assure'
    | '/products/geneie'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  TechnologyRoute: typeof TechnologyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/geneie': {
      id: '/products/geneie'
      path: '/geneie'
      fullPath: '/products/geneie'
      preLoaderRoute: typeof ProductsGeneieRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/assure': {
      id: '/products/assure'
      path: '/assure'
      fullPath: '/products/assure'
      preLoaderRoute: typeof ProductsAssureRouteImport
      parentRoute: typeof ProductsRoute
    }
  }
}

interface ProductsRouteChildren {
  ProductsAssureRoute: typeof ProductsAssureRoute
  ProductsGeneieRoute: typeof ProductsGeneieRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsAssureRoute: ProductsAssureRoute,
  ProductsGeneieRoute: ProductsGeneieRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ProductsRoute: ProductsRouteWithChildren,
  TechnologyRoute: TechnologyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
